In [15]:
'Python' != "Python"

False

In [20]:
0 == obj_bool

True

In [22]:
1.0 == True

True

In [26]:
0.0 == False

True

In [30]:
"1.0" == 1.0

False

In [34]:
"1" == 1.0

False

In [36]:
"0" == False

False

In [39]:
1 == "True"

False

In [43]:
0 < 2 <= 3

True

In [44]:
3 >= 2 > 0

True

In [45]:
import numpy as np
import pandas as pd

In [61]:
obj_tupla = tuple(np.random.randint(1, 10, 6))
obj_tupla_I = obj_tupla[:]
obj_tupla_II = obj_tupla[:]
print(f"{obj_tupla_I}\n{obj_tupla_II}")

(5, 6, 3, 8, 8, 5)
(5, 6, 3, 8, 8, 5)


In [62]:
obj_tupla_I == obj_tupla_II

True

In [63]:
obj_lista_II = list(obj_tupla_II)
obj_lista_II

[5, 6, 3, 8, 8, 5]

In [64]:
obj_tupla_I == obj_lista_II

False

In [65]:
obj_tupla_I = tuple(np.random.randint(1, 10, 6))
obj_tupla_II = tuple(np.random.randint(1, 10, 6))
print(f"{obj_tupla_I}\n{obj_tupla_II}")

(8, 1, 7, 2, 6, 2)
(9, 4, 7, 4, 8, 2)


In [66]:
obj_tupla_I == obj_tupla_II

False

In [68]:
obj_list_I = list(np.random.randint(1, 10, 6))
obj_list_II = list(np.random.randint(1, 10, 6))
print(f"{obj_list_I == obj_list_II}")

False


In [77]:
obj_numpy_I = np.random.randint(1, 10, 6)
obj_numpy_II = np.random.randint(1, 10, 6)
print(f"{obj_numpy_I}\n{obj_numpy_II}")

[3 6 1 1 8 6]
[6 3 1 5 5 7]


In [80]:
obj_numpy_I == obj_numpy_II

array([False, False,  True, False, False, False])

In [ ]:
obj_numpy_I[obj_numpy_I == obj_numpy_II]

array([1])

In [81]:
obj_numpy_I[obj_numpy_I != obj_numpy_II]

array([3, 6, 1, 8, 6])

In [82]:
obj_numpy_I[obj_numpy_I >= obj_numpy_II]

array([6, 1, 8])

In [83]:
obj_numpy_I

array([3, 6, 1, 1, 8, 6])

In [85]:
obj_numpy_I != 1

array([ True,  True, False, False,  True,  True])

In [86]:
obj_numpy_I >= 5

array([False,  True, False, False,  True,  True])

In [88]:
array = np.asarray(
    [obj_numpy_I,
    obj_numpy_II,
    obj_numpy_I,
    obj_numpy_II,
    obj_numpy_I,
    obj_numpy_II,]
)
array

array([[3, 6, 1, 1, 8, 6],
       [6, 3, 1, 5, 5, 7],
       [3, 6, 1, 1, 8, 6],
       [6, 3, 1, 5, 5, 7],
       [3, 6, 1, 1, 8, 6],
       [6, 3, 1, 5, 5, 7]])

In [90]:
obj_data = pd.DataFrame(array)
obj_data

,0,1,2,3,4,5
0,3,6,1,1,8,6
1,6,3,1,5,5,7
2,3,6,1,1,8,6
3,6,3,1,5,5,7
4,3,6,1,1,8,6
5,6,3,1,5,5,7


In [92]:
obj_data == 1

,0,1,2,3,4,5
0,False,False,True,True,False,False
1,False,False,True,False,False,False
2,False,False,True,True,False,False
3,False,False,True,False,False,False
4,False,False,True,True,False,False
5,False,False,True,False,False,False


In [106]:
obj_data[(1 < obj_data) & (obj_data <= 5)]

,0,1,2,3,4,5
0,3.0,NaN,NaN,NaN,NaN,NaN
1,NaN,3.0,NaN,5.0,5.0,NaN
2,3.0,NaN,NaN,NaN,NaN,NaN
3,NaN,3.0,NaN,5.0,5.0,NaN
4,3.0,NaN,NaN,NaN,NaN,NaN
5,NaN,3.0,NaN,5.0,5.0,NaN


In [93]:
obj_data > 2

,0,1,2,3,4,5
0,True,True,False,False,True,True
1,True,True,False,True,True,True
2,True,True,False,False,True,True
3,True,True,False,True,True,True
4,True,True,False,False,True,True
5,True,True,False,True,True,True


In [94]:
obj_data[obj_data > 2]

,0,1,2,3,4,5
0,3,6,NaN,NaN,8,6
1,6,3,NaN,5.0,5,7
2,3,6,NaN,NaN,8,6
3,6,3,NaN,5.0,5,7
4,3,6,NaN,NaN,8,6
5,6,3,NaN,5.0,5,7


In [96]:
obj_data[0] > 3

0    False
1     True
2    False
3     True
4    False
5     True
Name: 0, dtype: bool

In [98]:
obj_data.loc[4] != 1

0     True
1     True
2    False
3    False
4     True
5     True
Name: 4, dtype: bool

In [100]:
obj_data == obj_numpy_II

,0,1,2,3,4,5
0,False,False,True,False,False,False
1,True,True,True,True,True,True
2,False,False,True,False,False,False
3,True,True,True,True,True,True
4,False,False,True,False,False,False
5,True,True,True,True,True,True


In [101]:
obj_data

,0,1,2,3,4,5
0,3,6,1,1,8,6
1,6,3,1,5,5,7
2,3,6,1,1,8,6
3,6,3,1,5,5,7
4,3,6,1,1,8,6
5,6,3,1,5,5,7


In [103]:
obj_numpy_II

array([6, 3, 1, 5, 5, 7])

In [108]:
len(obj_data == obj_numpy_II)

6

In [109]:
len(obj_data)

6

In [110]:
obj_data == obj_numpy_II

,0,1,2,3,4,5
0,False,False,True,False,False,False
1,True,True,True,True,True,True
2,False,False,True,False,False,False
3,True,True,True,True,True,True
4,False,False,True,False,False,False
5,True,True,True,True,True,True
